# Generated by Django 4.2.4 on 2023-08-21 01:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
    ]
