# Generated by Django 4.2.4 on 2023-08-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_post_is_published_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('blog', 'Blog')], max_length=20),
        ),
    ]
