# Generated by Django 4.2.4 on 2023-10-24 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_post_date_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=140)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
