# Generated by Django 4.2.4 on 2023-10-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
